<a href="https://colab.research.google.com/github/DanielMode/Hamoye/blob/master/quiz%20code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:

import numpy as np
import pandas as pd

#create identity matrix
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#read data from file in github
url = "https://raw.githubusercontent.com/DanielMode/Hamoye/master/fuel_ferc1.csv"
data = pd.read_csv(url)
data.head()

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [23]:
#get general info about the fuel data
data.describe(include='all')

record_id  ...  fuel_cost_per_mmbtu
count                     29523  ...         29523.000000
unique                    29523  ...                  NaN
top     f1_fuel_2006_12_127_1_8  ...                  NaN
freq                          1  ...                  NaN
mean                        NaN  ...            19.304354
std                         NaN  ...          2091.540939
min                         NaN  ...           -41.501000
25%                         NaN  ...             1.940000
50%                         NaN  ...             4.127000
75%                         NaN  ...             7.745000
max                         NaN  ...        359278.000000

[11 rows x 11 columns]

In [37]:
# to find the year with the highest average fuel cost per unit delivered
data.groupby('report_year')['fuel_cost_per_unit_delivered'].mean()

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64

In [38]:
# to find the fuel type code with the lowest average fuel cost per unit burned
data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

In [32]:
# to find correlation in the data
data.corr()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
utility_id_ferc1                      1.000000  ...             0.006122
report_year                           0.093323  ...             0.010261
fuel_qty_burned                      -0.057447  ...            -0.001896
fuel_mmbtu_per_unit                  -0.066946  ...            -0.005884
fuel_cost_per_unit_burned            -0.037863  ...            -0.000437
fuel_cost_per_unit_delivered         -0.016414  ...            -0.000109
fuel_cost_per_mmbtu                   0.006122  ...             1.000000

[7 rows x 7 columns]

In [36]:
data.groupby('report_year')['fuel_cost_per_unit_burned'].pct_change()

0             NaN
1       -0.000538
2        1.137783
3        0.188570
4       -0.941326
           ...   
29518   -0.650840
29519   -0.236402
29520    0.306849
29521   -0.358491
29522   -1.000000
Name: fuel_cost_per_unit_burned, Length: 29523, dtype: float64